---
run:
  timeout: 5m
  go: "1.23"

linters-settings:
  errcheck:
    check-blank: true

  lll:
    line-length: 120
    tab-width: 4

linters:
  disable-all: true
  enable:
    - gofmt
    - errcheck
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
