---
name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - catalog-info.yaml
      - renovate.json

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version: '1.23'
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6
        with:
          version: v1.62.0
          args: --timeout=5m
          only-new-issues: true
      - name: Run linter
        run: golangci-lint run
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22', '1.23']
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: make test
  build:
    name: build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: '1.23'
          cache: true
      - name: Build
        run: |
          VERSION=${{ github.ref_name }}
          if [[ "${{ github.ref_type }}" == "branch" ]]; then
            VERSION="${VERSION}-${GITHUB_SHA::8}"
          fi
          go build -ldflags "-X main.version=${VERSION}" -o bin/sigstore-certificate-maker ./...
      - name: Upload binary
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: sigstore-certificate-maker
          path: bin/sigstore-certificate-maker
